name: repo_tagger
description: Front end application for github tagger

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State manager
  get: ^3.4.0

  # Network
  dio: ^3.0.9
  retrofit: ^1.3.4

  # UI/widgets
  flutter_typeahead_web: ">=1.0.0 <2.0.0"
  flutter_markdown: ^0.4.2

  # Misc
  logger: ^0.9.1
  shared_preferences: ^0.5.8

  # FIXME: may not be needed.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Analyzer
  effective_dart: ^1.2.0

  # Codegen/Builders
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  retrofit_generator: ^1.3.4

flutter:
  uses-material-design: true